### ISSUE TITLE
SIGSEGV in graphqlbackend.searchTree when there are lots of "context canceled" errors

### ISSUE THREAD

**Issue by sfllaw** [sourcegraph/issues#75]
- Issue type: Bug report
- Sourcegraph version: 2.7.6 (15051_2018-05-08_e88fa63) `sourcegraph/server:insiders`
- OS Version: amzn2-ami-hvm-2017.12.0.20180328.1-x86_64-gp2 (ami-07eb707f)
- Docker version:
```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built:        Tue Nov 14 22:03:51 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   402dd4a/17.06.2-ce
 Built:        Tue Nov 14 22:04:39 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Under heavy load, `frontend` fails with the following panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12022b3]
goroutine 10917893 [running]:
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/graphqlbackend.toGitCommitResolver(0xc4567b25e0, 0x0, 0xc493136d00)
	/buildkite/builds/buildkite-agent-58c8f5dbf9-d2dns/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/internal/graphqlbackend/git_commit.go:45 +0x33
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/graphqlbackend.(*repositoryResolver).Commit(0xc4567b25e0, 0x1c887c0, 0xc423fa4900, 0xc4567b2600, 0xc4246bdfc8, 0xbeb4a1880de72e6a, 0x1b43a457)
	/buildkite/builds/buildkite-agent-58c8f5dbf9-d2dns/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/internal/graphqlbackend/repository.go:108 +0x83
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/graphqlbackend.searchTreeForRepo(0x1c887c0, 0xc423fa4900, 0x0, 0x0
, 0xc48e643f80, 0xc425923a20, 0x8, 0xc493136d00, 0xc46307f230, 0x23, ...)
	/buildkite/builds/buildkite-agent-58c8f5dbf9-d2dns/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/internal/graphqlbackend/search.go:555 +0x12e
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/graphqlbackend.searchTree.func1(0xc463cd7290, 0x0, 0x0, 0xc48e643f80, 0xc425923a20, 0x8, 0x64, 0xc46f43c600, 0xc442bbc240, 0xc48e643fc0, ...)
	/buildkite/builds/buildkite-agent-58c8f5dbf9-d2dns/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/internal/graphqlbackend/search.go:519 +0xae
created by github.com/sourcegraph/sourcegraph/cmd/frontend/internal/graphqlbackend.searchTree
	/buildkite/builds/buildkite-agent-58c8f5dbf9-d2dns/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/internal/graphqlbackend/search.go:518 +0x206
Terminating frontend
```

This occurs alongside many error messages that look like:

```
frontend | t=2018-05-08T20:54:56+0000 lvl=eror msg="error getting search suggestions: " error="exec `git rev-parse` failed with stderr: : context canceled (and 19 more)"
```

There is also another panic reported by `frontend` that looks related:

```
graphql: panic occurred: runtime error: invalid memory address or nil pointer dereference
goroutine 10785574 [running]:
github.com/sourcegraph/sourcegraph/vendor/github.com/graph-gophers/graphql-go/log.(*DefaultLogger).LogPanic(0x2741890, 0x1c88880, 0xc45bee3500, 0x15ed260, 0x26e1e30)
	/buildkite/builds/buildkite-agent-58c8f5dbf9-d2dns/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/vendor/github.com/graph-gophers/graphql-go/log/log.go:21 +0x77
github.com/sourcegraph/sourcegraph/vendor/github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection.func2.1(0xc476f40600, 0x1c88880, 0xc45bee3500, 0xc43d5a3ef8, 0xc45e0e1e80)
	/buildkite/builds/buildkite-agent-58c8f5dbf9-d2dns/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/vendor/github.com/graph-gophers/graphql-go/internal/exec/exec.go:161 +0x87
panic(0x15ed260, 0x26e1e30)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/graphqlbackend.toGitCommitResolver(0xc4a346b190, 0x0, 0xc444444a00)
	/buildkite/builds/buildkite-agent-58c8f5dbf9-d2dns/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/internal/graphqlbackend/git_commit.go:45 +0x33
github.com/sourcegraph/sourcegraph/cmd/frontend/internal/graphqlbackend.(*repositoryResolver).Commit(0xc4a346b190, 0x1c88880, 0xc46107e180, 0xc4a346a3b0, 0x0, 0x0, 0x0)
	/buildkite/builds/buildkite-agent-58c8f5dbf9-d2dns/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/cmd/frontend/internal/graphqlbackend/repository.go:108 +0x83
reflect.Value.call(0x17bc9c0, 0xc4461a8620, 0xa93, 0x17fddb9, 0x4, 0xc46107e270, 0x2, 0x2, 0x1c, 0xc46107e270, ...)
	/usr/local/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x17bc9c0, 0xc4461a8620, 0xa93, 0xc46107e270, 0x2, 0x2, 0xa93, 0x2, 0xc43f958000)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/sourcegraph/sourcegraph/vendor/github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection.func2(0xc476f40600, 0x1c88880, 0xc45bee3500, 0xc45e0e1e80, 0xc4461a8b40, 0xc43d5a3f40, 0x1c88880, 0xc46107e180, 0x0)
	/buildkite/builds/buildkite-agent-58c8f5dbf9-d2dns/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/vendor/github.com/graph-gophers/graphql-go/internal/exec/exec.go:183 +0x372
github.com/sourcegraph/sourcegraph/vendor/github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection(0x1c88880, 0xc45bee3500, 0xc476f40600, 0xc4461a8b40, 0xc45e0e1e80, 0xc45097fd01)
	/buildkite/builds/buildkite-agent-58c8f5dbf9-d2dns/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/vendor/github.com/graph-gophers/graphql-go/internal/exec/exec.go:193 +0x1aa
github.com/sourcegraph/sourcegraph/vendor/github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections.func1(0xc477f22570, 0xc476f40600, 0x1c88880, 0xc45bee3500, 0xc45e0e13c0, 0xc4461a8b40)
	/buildkite/builds/buildkite-agent-58c8f5dbf9-d2dns/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/vendor/github.com/graph-gophers/graphql-go/internal/exec/exec.go:74 +0x16c
created by github.com/sourcegraph/sourcegraph/vendor/github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections
	/buildkite/builds/buildkite-agent-58c8f5dbf9-d2dns/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/vendor/github.com/graph-gophers/graphql-go/internal/exec/exec.go:70 +0x476
```

**Comment by nicksnyder** [comment]
Thanks for the bug report! I have a PR open to fix this panic.

Out of curiosity, how did you trigger this panic in the product? Just by doing a lot of searches?

**Comment by sfllaw** [comment]
@nicksnyder We seem to be triggering this panic by having around 3000 repositories and we set `maxReposToSearch` to allow all of them to be searched at once.

**Comment by nicksnyder** [comment]
Thanks for the context. This bug only existed in our insiders build and is now fixed in the latest insiders image.

**Comment by sfllaw** [comment]
This has not recurred since we upgraded to build 15143_2018-05-09_c31b624.
